FROM node:lts-slim
RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app
COPY . .
USER root
RUN npm install
RUN npm install -g react-scripts
RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

EXPOSE 3000

CMD [ "npm", "start" ]